const fs=require('fs');const path=require('path');const crypto=require('crypto');
class JsonStore{
  constructor(filePath){this.filePath=filePath;fs.mkdirSync(path.dirname(filePath),{recursive:true});this.data=this.load();}
  blank(){return{schema:3,students:{},commands:[],teachers:{},corporateActions:[],settings:{},audit:[]};}
  load(){try{if(!fs.existsSync(this.filePath))return this.blank();const p=JSON.parse(fs.readFileSync(this.filePath,'utf8'));return{schema:3,students:p.students||{},commands:Array.isArray(p.commands)?p.commands:[],teachers:p.teachers||{},corporateActions:Array.isArray(p.corporateActions)?p.corporateActions:[],settings:p.settings||{},audit:Array.isArray(p.audit)?p.audit:[]};}catch(e){const backup=`${this.filePath}.broken-${Date.now()}`;try{fs.copyFileSync(this.filePath,backup)}catch{}console.error('[저장소] 기존 서버 데이터 읽기 실패. 새 저장소로 시작합니다:',e.message);return this.blank();}}
  save(){const tmp=`${this.filePath}.tmp`;fs.writeFileSync(tmp,JSON.stringify(this.data,null,2),'utf8');fs.renameSync(tmp,this.filePath);}
  upsertStudent(meta){const prev=this.data.students[meta.accountId]||{};this.data.students[meta.accountId]={...prev,...meta,registeredAt:prev.registeredAt||new Date().toISOString(),updatedAt:new Date().toISOString()};this.save();return this.data.students[meta.accountId];}
  getStudent(id){return this.data.students[id]||null;}
  listStudents({grade,classNo}={}){return Object.values(this.data.students).filter(s=>(!grade||String(s.grade)===String(grade))&&(!classNo||String(s.classNo)===String(classNo))).sort((a,b)=>Number(a.studentNo||0)-Number(b.studentNo||0)||String(a.name||'').localeCompare(String(b.name||''),'ko'));}
  addCommands(commands,actor){const now=new Date().toISOString();for(const c of commands)this.data.commands.push({id:c.id||crypto.randomUUID(),accountId:c.accountId,amount:Math.trunc(c.amount),reason:String(c.reason||'').slice(0,120),createdAt:now,createdBy:actor.id,createdByName:actor.name,status:'PENDING',appliedAt:null,appliedAmount:null,cancelledAt:null,reversalOf:c.reversalOf||null,reversedBy:null});this.audit('COMMAND_CREATE',actor,{count:commands.length});this.trim();this.save();}
  getPendingCommands(id){return this.data.commands.filter(c=>c.accountId===id&&c.status==='PENDING');}
  markCommandsApplied(results){const m=new Map(results.map(r=>[r.id,r]));for(const c of this.data.commands){const r=m.get(c.id);if(!r||c.status!=='PENDING')continue;c.status='APPLIED';c.appliedAt=r.appliedAt||new Date().toISOString();c.appliedAmount=Math.trunc(r.appliedAmount||0);}this.save();}
  listCommands({grade,classNo,limit=300}={}){const ss=this.data.students;return[...this.data.commands].filter(c=>{const s=ss[c.accountId];return s&&(!grade||String(s.grade)===String(grade))&&(!classNo||String(s.classNo)===String(classNo));}).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,limit).map(c=>({...c,student:ss[c.accountId]}));}
  cancelOrReverseCommand(id,actor){const c=this.data.commands.find(x=>x.id===id);if(!c)throw new Error('명령을 찾을 수 없습니다.');if(c.status==='CANCELLED')throw new Error('이미 취소된 명령입니다.');if(c.reversedBy)throw new Error('이미 취소(반대 거래) 처리된 명령입니다.');if(c.status==='PENDING'){c.status='CANCELLED';c.cancelledAt=new Date().toISOString();c.cancelledBy=actor.id;this.audit('COMMAND_CANCEL',actor,{commandId:id});this.save();return{kind:'cancelled',command:c};}if(c.status==='APPLIED'){const reversal={id:crypto.randomUUID(),accountId:c.accountId,amount:-Math.trunc(c.appliedAmount||0),reason:`취소: ${c.reason||'교사 지급/차감'}`,reversalOf:c.id},now=new Date().toISOString();this.data.commands.push({...reversal,createdAt:now,createdBy:actor.id,createdByName:actor.name,status:'PENDING',appliedAt:null,appliedAmount:null,cancelledAt:null,reversedBy:null});c.reversedBy=reversal.id;this.audit('COMMAND_REVERSE',actor,{commandId:id,reversalId:reversal.id});this.trim();this.save();return{kind:'reversal',command:reversal};}throw new Error('현재 상태에서는 취소할 수 없습니다.');}
  createTeacher({id,name,grade,classNo,passwordHash,passwordSalt},actor){if(!id)throw new Error('교사 아이디가 필요합니다.');this.data.teachers[id]={id,name,grade:String(grade||''),classNo:String(classNo||''),passwordHash,passwordSalt,enabled:true,createdAt:this.data.teachers[id]?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};this.audit('TEACHER_UPSERT',actor,{teacherId:id,grade,classNo});this.save();return this.data.teachers[id];}
  listTeachers(){return Object.values(this.data.teachers).map(({passwordHash,passwordSalt,...rest})=>rest);}
  getTeacher(id){return this.data.teachers[id]||null;}
  getSetting(key,fallback=null){return this.data.settings[key]??fallback;}
  setSetting(key,value,actor){this.data.settings[key]=value;this.audit('SETTING_CHANGE',actor,{key,value});this.save();return value;}
  addCorporateAction(action,actor={id:'system',name:'system'}){const now=new Date().toISOString();const rec={id:action.id||crypto.randomUUID(),type:String(action.type||''),oldCode:String(action.oldCode||''),newCode:String(action.newCode||''),oldName:String(action.oldName||'').slice(0,80),newName:String(action.newName||'').slice(0,80),ratioNum:Number(action.ratioNum||1),ratioDen:Number(action.ratioDen||1),settlementPrice:Number(action.settlementPrice||0),cashPerOldShare:Number(action.cashPerOldShare||0),effectiveDate:String(action.effectiveDate||now.slice(0,10)),note:String(action.note||'').slice(0,200),source:String(action.source||'MANUAL'),sourceKey:String(action.sourceKey||''),status:String(action.status||'ACTIVE'),createdAt:now,createdBy:actor.id,createdByName:actor.name};this.data.corporateActions.push(rec);this.audit('CORPORATE_ACTION_CREATE',actor,{id:rec.id,type:rec.type,oldCode:rec.oldCode,newCode:rec.newCode});this.trim();this.save();return rec;}
  upsertAutoCorporateAction(action){if(action.type==='NEW_LISTING')return null;const existing=action.sourceKey&&this.data.corporateActions.find(x=>x.sourceKey===action.sourceKey);if(existing)return existing;return this.addCorporateAction({...action,source:'AUTO',status:action.requiresReview?'PENDING_REVIEW':'ACTIVE',note:action.type==='REMOVED'?'공식 종목 마스터에서 사라져 거래를 자동 차단했습니다. 합병·코드변경·상장폐지 여부는 관리자 확인이 필요합니다.':action.note||''},{id:'system',name:'자동 종목감지'});}
  listCorporateActions({limit=500}={}){return[...this.data.corporateActions].sort((a,b)=>String(b.effectiveDate).localeCompare(String(a.effectiveDate))||String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,limit);}
  getEffectiveCorporateActions(){const today=new Date().toISOString().slice(0,10);return this.data.corporateActions.filter(a=>a.status==='ACTIVE'&&String(a.effectiveDate||'')<=today).sort((a,b)=>String(a.effectiveDate).localeCompare(String(b.effectiveDate))||String(a.createdAt).localeCompare(String(b.createdAt)));}
  updateCorporateAction(id,patch,actor){const a=this.data.corporateActions.find(x=>x.id===id);if(!a)throw new Error('기업행동 기록을 찾을 수 없습니다.');for(const k of ['status','settlementPrice','cashPerOldShare','note','ratioNum','ratioDen','newCode','newName'])if(k in patch)a[k]=patch[k];a.updatedAt=new Date().toISOString();this.audit('CORPORATE_ACTION_UPDATE',actor,{id,patch});this.save();return a;}
  audit(action,actor,details={}){this.data.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),action,actorId:actor?.id||'system',actorName:actor?.name||'system',details});if(this.data.audit.length>5000)this.data.audit.splice(0,this.data.audit.length-5000);}
  trim(){if(this.data.commands.length>20000)this.data.commands.splice(0,this.data.commands.length-20000);if(this.data.corporateActions.length>5000)this.data.corporateActions.splice(0,this.data.corporateActions.length-5000);}
}
module.exports={JsonStore};
